name: form_bloc_melos

packages:
  - form_bloc_web
  - packages/flutter_form_bloc
  - packages/form_bloc

scripts:
  analyze:
    exec: dart analyze .

  clear:
    description: Run Flutter Clean
    exec: flutter clean

  fix:
    description: Run Dart Fix in All the packages
    exec: dart fix --apply
